### ISSUE TITLE
Oauth support?

### ISSUE THREAD

**Issue by nogweii** [oVirt/terraform-provider-ovirt#149]
It would nice to not have to pass a password, but instead an oauth token, as the credential to authenticate with oVirt. Not sure how to actually do that, I guess an oauth device flow would be used?

**Comment by imjoey** [comment]
Hi @evaryont , thanks for reporting. As far as I know, currently oVirt is able to work with Kerberos authentication, which does not need to provider user password.  So we could add a new parameter named `kerberos` of `schema.TypeBool` type in provider,  to indicate if use Kerberos authentication instead of basic one. Please let me know if it's OK for you and any feedbacks are appreciated.

**Comment by rgolangh** [comment]
I'm not sure what @evaryont you mean buy oauth device flow. 

oVirt support oauth, and in order to get your token you need an api call, both for Basic auth, and SPNEGO (for kerb) , and every API request can be made with that token afterwards.

We do lack in oVirt proper token management, for example to let a user define number of tokens, delete them, control their permission and so on.

@imjoey there is no distinction between token types. Once you have a token just pass it in the header
```
curl ­ ­\
    -H "Authorization: Bearer mWIwC8zJOmLoysbiPEDyLIhUMm1IV9ltW2osSMfh85hJ9nmY­Gph_aalD4FqjTMRQYSwjFuiqIWqDJwD­2dYVQ" ­\
    -L https://engine/ovirt­engine/api
```

**Comment by imjoey** [comment]
@rgolangh  Apology for misunderstanding the role of kerberos. Thank you very much for your clarification.

**Comment by evaryont** [comment]
@rgolangh I'm referring to https://oauth.net/2/device-flow/ - you may have seen it in other apps. They will tell you to go to a page, and then type in a code into them from the page. (For example, Youtube on TVs will ask for a 6 digit code generated by the Youtube website in order to log in as a user.)

I'm not sure if this particular type of oAuth flow is supported by oVirt, however.

**Comment by emesika** [comment]
Sorry for the delay, we are doing a cleanup on all issues in order to be more responsive, is this issue still relevant or we can delete it ?

**Comment by emesika** [comment]
closing this issue , please feel free to reopen if still relevant and provide full details
