### ISSUE TITLE
How does one consume the provider?

### ISSUE THREAD

**Issue by rgolangh** [oVirt/terraform-provider-ovirt#165]
What's the way we should publish the provider and make people consume it?

Is it by [publishing and share on the terraform registry](https://www.terraform.io/docs/registry/modules/publish.html)

Or by publishing an rpm to the oVirt repo? or both?

How is this community expecting to consume it, or how do they consume any other tf module?

Feedback is welcome

**Comment by imjoey** [comment]
Publishing commonly used oVirt modules to terraform registry is good way to provide reusable module for users. To achieve that, we could establish a new Github organization account, probably named `terraform-ovirt-modules` and then we develop each module and host it on a repository under that account.

IMHO, users would prefer publicly available modules rather than rpm packages as they could be downloaded automatically by running `terraform init` command.

Of course, I think the most important thing is improving this project to make it a official provider by hashicorp, as described in [Terraform Provider Development Program
](https://www.terraform.io/guides/terraform-provider-development-program.html). After that, uses could ease the consuming process because the provider is no need to be manually download/build/install.

**Comment by imjoey** [comment]
Hi, I found a project hosted at [GoogleCloudPlatform/terraformer](https://github.com/GoogleCloudPlatform/terraformer). This project aims to help users to generate terraform files from existing infrastructure. I would spend some time on the oVirt integration that it probably would provide a smooth way for users to leverage the terraform provider to manage existing oVirt platform. Very thankful for any feedback.

**Comment by sandrobonazzola** [comment]
Any update?

**Comment by thomasfinstad** [comment]
With the new 0.13 (currently beta) update community providers can be directly consumed from hasicorps registry, it might be the best/most intuitive way to publish the provider. https://www.terraform.io/docs/registry/providers/publishing.html

**Comment by emesika** [comment]
Sorry for the delay, we are doing a cleanup on all issues in order to be more responsive, is this issue still relevant or we can delete it ?

**Comment by sandrobonazzola** [comment]
@emesika I think we need to investigate the publishing on the hasicorps registry

**Comment by janosdebugs** [comment]
The provider is now released in the registry: https://registry.terraform.io/providers/oVirt/ovirt/
