### ISSUE TITLE
Website docs are broken

### ISSUE THREAD

**Issue by mleone87** [oVirt/terraform-provider-ovirt#209]
Steps to reproduce:

1. Pulling latest code
2. make website
3. curl http://localhost:4567/docs/providers/ovirt
`<html><head></head><body><h1>File Not Found</h1><p>/docs/providers/ovirt</p></body></html>`

Any help on this?

thanks!

**Comment by johnsimcall** [comment]
I managed to hack the resulting docker container/image enough to get it to work.  These are the commands I executed to "fix" it for me...

```bash
$ sudo docker ps
$ sudo docker exec -it ${NAME_OF_CONTAINER} /bin/bash
bash-4.4# apk add rsync
bash-4.4# rsync -av /website/ /terraform-website/source/
```

**Comment by nickbouwhuis** [comment]
Looks like this problem is ongoing. And the fix suggested by @johnsimcall is no longer working. 

I'll submit a pull request once I get it sorted out.

**Comment by nickbouwhuis** [comment]
Seems like the docs are broken because Terraform moved to `registry.terraform.io` for documentation on providers. It seems like there isn't a repository for the registry website and only the owners of this repo can add it there.

Until then, you either have to check out an older version of the `github.com/hashicorp/terraform-website` repo or read the markdown files as they exist in this repo.
