### ISSUE TITLE
How to clone VM

### ISSUE THREAD

**Issue by xiriox** [oVirt/terraform-provider-ovirt#248]
Hi,

In ovirt examples, i found a argument "clone" (optional, false by default) in ovirt_vm resource, but in the documentation, do not apear.

Can i clone an VM with that argument if i put in the template_id the VM_id of the origin?

If not is that, how can i clone a VM on ovirt/RHEV?

Thank you 

Best regards

**Comment by bratucornel** [comment]
Hi,

```txt
Virtual machines created from a template depend on that template. 
So you cannot remove a template from the Engine if a virtual machine was created from that template. 
However, you can clone a virtual machine from a template to remove the dependency on that template.

---

Cloning a virtual machine may take some time. 
A new copy of the template’s disk must be created. During this time, the virtual machine’s status 
is first Image Locked, then Down.
```

[Creating a Virtual Machine Based on a Template](https://www.ovirt.org/documentation/virtual_machine_management_guide/#Creating_a_Virtual_Machine_Based_on_a_Template)

So, if you want to create a new vm and later want to delete that template, you need to set the `clone` parameter to `true`. Otherwise, when you want to delete that template, you will see an error like:

```
Operation canceled
Cannot delete Template. Template is being used by the following
ubuntu-20.04:
 * Cannot delete Template. Template is being used by the following VMs: my-vm-01, my-vm-02...
```

In oVirt > compute > Virtual Machines > your vm you can see if vm is cloned or thin provisioned.

Example:

```tf
resource "ovirt_vm" "my_vm" {
...
    name = "my-vm-01"
    clone = false
    memory = 1024
    cores = 1
...
}
```

Will produce an vm with `Template: ubuntu-20.04 (Thin/Dependent)`

and 

```tf
resource "ovirt_vm" "my_vm" {
...
    name = "my-vm-01"
    clone = true
    memory = 1024
    cores = 1
...
}
```

Will produce an vm with `Template: ubuntu-20.04 (Clone/Independent)`

Is the same behaviour for manually created vms via oVirt UI, when you can choose between thin and clone from Resource allocation > Storage allocation.

**Comment by xiriox** [comment]
ok, thank you!
