### ISSUE TITLE
Test framework

### ISSUE THREAD

**Issue by jake2184** [oVirt/terraform-provider-ovirt#289]
Hi,

Has progress been made on having a reliable test framework in place? With the deprecation of v1 of the terraform plugin SDK, I'd want to look at upgrading it (and supporting later TF versions), but don't want to bother unless the testing framework is in place and RedHat has bandwidth to review and merge.

**Comment by janosdebugs** [comment]
@jake2184 yes, we have made progress. Let me give you an overview of what we are currently doing:

1. We attempted to fix the tests [in this repo](https://github.com/oVirt/terraform-provider-ovirt/pull/277), but the change is too huge to merge.
2. We created a new [client library for oVirt](https://github.com/ovirt/go-ovirt-client), which is providing a clean and testable API to talk to oVirt.
3. We have also started an [experimental v2 build of a new TF provider](https://github.com/haveyoudebuggedit/terraform-provider-ovirt-ng) to explore if we can build an improved version. This would include solving some of the state management issues we have in the current provider, as well as having full test coverage. If it pans out, this will break backward compatibility, however. The experiment is barely a week old, so you'll have more to see there in 1-2 weeks.
4. In order to upgrade the TF provider SDK to v2, we also need to make the [openshift installer](https://github.com/openshift/installer) compatible. Currently, the installer only supports the v1 SDK, so until that is solved we can't move to v2.

We aim to switch to using go-ovirt-client in all components (TF provider, CSI driver, etc) and having a TF provider that contains most functionality by the end of the feature freeze of OpenShift 4.10, which is mid December. (That means either writing a new provider or patching this provider to a point where this can actually work.)

This timeline is fairly aggressive, but it is currently the highest priority task on my agenda and one of the major epics we have for 4.10, so it will get done. If you have capacity to help out, the best way to do so would be to port functionality to go-ovirt-client.

I would recommend holding off on porting this TF provider to v2 until we have a clearer picture of which variant we'd like to continue developing. (Note, even if we go the route of the new provider we are *not* going to wipe this one. It means that we will put our efforts into developing the new provider and publish it with Hashicorp.)

**Comment by jake2184** [comment]
ok, thanks for the comprehensive answer.

Looking at the go-ovirt-client, a number of things look extendable but the best way for me to test it is to be using the functionality in the TF provider - so I'll wait to see if the new one works out.

My inference from the above is that this provider will remain on the old, raw `go-ovirt`, rather than trying to port to the new `go-ovirt-client`. Is that correct? So a clean break of a new provider with a new ovirt SDK lib and TF SDK v2.

I'll check in in a few weeks to see where the focus is.

**Comment by janosdebugs** [comment]
@jake2184 yes, if the new TF provider pans out, then this provider stays go-ovirt (SDK), while the new will be built on go-ovirt-client. Eventually the new provider will provide all functionality of this provider and hopefully make this one obsolete.

To add context, I hate to throw good code away, but it does not seem that we could make the transition of this provider to go-ovirt-client just because the sheer amount of code we have to add.

**Comment by janosdebugs** [comment]
Hey @jake2184 I'm closing this issue and will be transferring the features planned for support as separate issues. Please watch this repository to keep track of our progress.
